name             'tomcat7'
maintainer       'Mark Morlino'
maintainer_email 'mark@gina.alaska.edu'
license          'All rights reserved'
description      'Installs/Configures tomcat7'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'
depends		 'ark'
depends		 'java'
depends		 'user'
supports	 'centos', '>= 6.0'
